
export const LOW_VALUE_ROUTE_PREFIXES = [
  "/product-tag/",
  "/tag/",
  "/category/",
  "/author/",
  "/cart/",
  "/checkout/",
  "/my-account/",
  "/product-category/",
];

export const ROUTE_CANONICAL_OVERRIDES: Record<string, string> = {
  /* ── Blog-post permalinks that should point at their canonical landing ── */
  "/2024/12/22/rfid-laundry-tags/": "/solutions/rfid-laundry-tags/",
  "/2024/12/24/rfid-event-wristband/": "/solutions/rfid-event-access-control/",
  "/2024/12/24/rfid-wooden-card/": "/compare/metal-vs-wood-vs-pvc-nfc-business-cards/",
  "/2024/12/25/rfid-hotel-key-card/": "/solutions/hotel-key-cards/",
  "/2025/11/04/mifare_plus_card/": "/compare/mifare-plus-ev2-vs-desfire-ev3/",

  /* ── Pre-revamp multilingual homes with no current equivalent ─────────
   * Old-era GSC shows clicks on these language homes; interim-target the
   * root until the language launches (then re-point per language). */
  "/it/": "/",
  "/fr/": "/",
  "/ru/": "/",
  "/da/": "/",

  /* ── Legacy recovery sync (mirror of vercel.json) ── */
  "/ar": "/",
  "/da": "/",
  "/ru": "/",
  "/fr": "/",
  "/it": "/",
  "/es/producto/java-card/": "/products/rfid-cards/java-card/",
  "/ru/produkt/java-card/": "/products/rfid-cards/java-card/",
  "/de/produkt/java-card/": "/products/rfid-cards/java-card/",
  "/fr/produit/java-card/": "/products/rfid-cards/java-card/",
  "/da/produkt/java-card/": "/products/rfid-cards/java-card/",
  "/it/prodotto/java-card/": "/products/rfid-cards/java-card/",
  "/resources/downloads/": "/resources/",
  "/downloads/gs1-sgtin-96-encoding-template.xlsx": "/resources/",
  "/downloads/hotel-key-card-artwork-template.pdf": "/resources/",
  "/downloads/dscsa-item-level-rfid-brief.pdf": "/resources/",
  "/en/rfid/": "/products/all/",
  "/product-tag/:path(.*)": "/products/all/",
  "/product-category/:path(.*)": "/products/all/",
  "/tag/:path(.*)": "/blog/",
  "/category/:path(.*)": "/blog/",
  "/author/:path(.*)": "/about/",
  "/cart/:path(.*)": "/",
  "/checkout/:path(.*)": "/",
  "/my-account/:path(.*)": "/",
  "/wp-content/:path(.*)": "/site-assets/wp-content/:path",


  /* ── Pre-revamp multilingual legacy recovery (GSC 2025-09→2026-02, exposure≥5) ── */
  "/ar/shop": "/",
  "/da/about": "/about/",
  "/da/kontakte": "/contact/",
  "/da/produkt/biltransponderchip": "/products/rfid-tags/",
  "/da/produkt/hotelnoglekort": "/products/rfid-cards/",
  "/da/produkt/legitimt-kort": "/products/rfid-cards/",
  "/da/produkt/mifare-desfire-ev2-kort": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/da/produkt/mifare-plus-card": "/products/rfid-cards/mifare-plus-se-card/",
  "/da/produkt/nfc-reader-writer-with-free-sdks": "/products/rfid-readers/",
  "/da/produkt/rfid-silikone-armband": "/products/rfid-wristbands/",
  "/da/produkt/t5577-kort": "/products/rfid-cards/",
  "/da/produktkategori/produkter/rfid-wristbands": "/products/rfid-wristbands/",
  "/da/produktkategori/urunler/rfid-wristbands": "/products/rfid-wristbands/",
  "/da/produktmaerke/emv-kort-med-dobbelt-graenseflade": "/products/rfid-cards/",
  "/da/produktmaerke/hotelnogler": "/products/rfid-keyfobs/",
  "/da/produktmaerke/nfc-card-reader-writer": "/products/rfid-readers/",
  "/da/produktmaerke/nfc-reader-writer": "/products/rfid-readers/",
  "/da/produktmaerke/printbare-rfid-kort": "/products/rfid-cards/",
  "/da/produktmaerke/smartkortskriver": "/products/rfid-cards/",
  "/da/shop": "/",
  "/de": "/",
  "/de/blog": "/",
  "/de/produkt-tag/flipper-zero-mifare-desfire": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/de/produkt/auto-transponderchip": "/products/rfid-tags/",
  "/de/produkt/google-review-nfc-card": "/products/rfid-cards/",
  "/de/produkt/hitag-2-karte": "/products/rfid-tags/",
  "/de/produkt/hotelschlusselkarten": "/products/rfid-cards/",
  "/de/produkt/legic-karte": "/products/rfid-cards/",
  "/de/produkt/mifare-desfire-ev2-cards": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/de/produkt/mifare-plus-card": "/products/rfid-cards/mifare-plus-se-card/",
  "/de/produkt/nfc-lese-schreibgerat-mit-kostenlosen-sdks": "/products/rfid-readers/",
  "/de/produkt/nfc-ring": "/products/rfid-wristbands/",
  "/de/produkt/rfid-event-armband-2": "/products/rfid-wristbands/",
  "/de/produkt/rfid-sticker-on-headlight": "/products/rfid-labels/",
  "/de/produkt/uhf-armband": "/products/rfid-wristbands/",
  "/de/produkt/wooden-rfid-card": "/products/rfid-cards/",
  "/de/produktkategorie/produkte": "/products/rfid-cards/",
  "/de/produktkategorie/produkte/rfid-labels": "/products/rfid-labels/",
  "/de/shop": "/",
  "/es": "/",
  "/es/blog": "/",
  "/es/contacto": "/contact/",
  "/es/etiqueta-del-producto/rfid-mifare-classic": "/products/rfid-cards/mifare-classic-1k-card/",
  "/es/producto/car-transponder-chip": "/products/rfid-tags/",
  "/es/producto/hitag-2-card": "/products/rfid-tags/",
  "/es/producto/hotel-key-cards": "/products/rfid-cards/",
  "/es/producto/mifare-desfire-cards": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/es/producto/mifare-desfire-ev2-cards": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/es/producto/mifare-plus-card": "/products/rfid-cards/mifare-plus-se-card/",
  "/es/producto/mifare-stickers": "/products/rfid-labels/",
  "/es/producto/nfc-reader-writer-with-free-sdks": "/products/rfid-readers/",
  "/es/producto/pulseras-rfid-para-hoteles": "/products/rfid-wristbands/",
  "/es/producto/tarjeta-legic": "/products/rfid-cards/",
  "/fa": "/",
  "/fa/%D8%A8%D8%B1%DA%86%D8%B3%D8%A8-%D9%85%D8%AD%D8%B5%D9%88%D9%84/%D8%AC%DB%8C%DA%A9%D8%A7%D9%BE-%DB%B4%DB%B0-%D9%87%D8%B2%D8%A7%D8%B1": "/",
  "/fa/%D8%A8%D8%B1%DA%86%D8%B3%D8%A8-%D9%85%D8%AD%D8%B5%D9%88%D9%84/%D8%AC%DB%8C%DA%A9%D8%A7%D9%BE-%DB%B4%DB%B0-%DA%A9%D8%A7%D8%B1%D8%AA-%D8%AE%D8%A7%D9%84%DB%8C": "/",
  "/fa/%D8%A8%D8%B1%DA%86%D8%B3%D8%A8-%D9%85%D8%AD%D8%B5%D9%88%D9%84/%DA%A9%D8%A7%D8%B1%D8%AA%D9%87%D8%A7%DB%8C-%D8%AC%D8%A7%D9%88%D8%A7-%D8%AC%DB%8C%DA%A9%D8%A7%D9%BE": "/",
  "/fa/%D8%A8%D8%B1%DA%86%D8%B3%D8%A8-%D9%85%D8%AD%D8%B5%D9%88%D9%84/hid-125-khz-proximity-cards": "/products/rfid-cards/",
  "/fa/%D8%A8%D8%B1%DA%86%D8%B3%D8%A8-%D9%85%D8%AD%D8%B5%D9%88%D9%84/hid-proximity-fob": "/products/rfid-keyfobs/",
  "/fa/%D9%85%D8%AD%D8%B5%D9%88%D9%84/%DA%A9%D8%A7%D8%B1%D8%AA%D9%87%D8%A7%DB%8C-%D9%85%D8%A7%DB%8C%D9%81%D8%B1-%D8%AF%D8%B3%D9%81%D8%A7%DB%8C%D8%B1": "/",
  "/fa/%D9%85%D8%AD%D8%B5%D9%88%D9%84/%DA%A9%D8%A7%D8%B1%D8%AA%D9%87%D8%A7%DB%8C-%D9%85%D8%A7%DB%8C%D9%81%D8%B1-%D8%AF%D8%B3%D9%81%D8%A7%DB%8C%D8%B1-ev2": "/",
  "/fa/%D9%85%D8%AD%D8%B5%D9%88%D9%84/%DA%A9%D8%A7%D8%B1%D8%AA-%D8%B5%D8%AF%D9%81%DB%8C": "/",
  "/fa/%D9%85%D8%AD%D8%B5%D9%88%D9%84/acr122u": "/products/rfid-readers/desktop-nfc-reader-encoder/",
  "/fr/about": "/about/",
  "/fr/contact": "/contact/",
  "/fr/etiquette-de-produit/coding-nfc-tags": "/products/rfid-tags/",
  "/fr/etiquette-de-produit/mifare-classic-nfc": "/products/rfid-cards/mifare-classic-1k-card/",
  "/fr/etiquette-de-produit/nfc-tap-here-sticker": "/products/rfid-labels/",
  "/fr/produit/car-transponder-chip": "/products/rfid-tags/",
  "/fr/produit/carte-java": "/",
  "/fr/produit/carte-legendaire": "/",
  "/fr/produit/felica-card": "/products/rfid-cards/",
  "/fr/produit/hitag-2-card": "/products/rfid-tags/",
  "/fr/produit/mifare-desfire-ev2-cards": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/fr/produit/mifare-plus-card": "/products/rfid-cards/mifare-plus-se-card/",
  "/fr/produit/nfc-reader-writer-with-free-sdks": "/products/rfid-readers/",
  "/he": "/",
  "/he/%D7%9E%D7%95%D6%BC%D7%A6%D6%B8%D7%A8/%D7%9B%D7%A8%D7%98%D7%99%D7%A1%D7%99-%D7%9E%D7%99%D7%A4%D7%90%D7%A8-%D7%93%D7%A1%D7%A4%D7%99%D7%99%D7%A8": "/",
  "/he/%D7%9E%D7%95%D6%BC%D7%A6%D6%B8%D7%A8/%D7%9B%D7%A8%D7%98%D7%99%D7%A1%D7%99-nfc": "/",
  "/he/%D7%9E%D7%95%D6%BC%D7%A6%D6%B8%D7%A8/uhf-wristband": "/products/rfid-wristbands/",
  "/he/%D7%AA%D7%92-%D7%9E%D7%95%D7%A6%D7%A8/125khz-rfid-sticker": "/products/rfid-labels/",
  "/he/%D7%AA%D7%92-%D7%9E%D7%95%D7%A6%D7%A8/smartcard-writer": "/products/rfid-readers/",
  "/he/%D7%AA%D7%92-%D7%9E%D7%95%D7%A6%D7%A8/washable-rfid-tags": "/products/rfid-tags/",
  "/he/product-category/products/rfid-cards": "/products/rfid-cards/",
  "/he/product-category/produkte/rfid-labels": "/products/rfid-labels/",
  "/he/product-category/produtos/rfid-keyfobs": "/products/rfid-cards/",
  "/he/product-category/urunler/rfid-tags": "/products/rfid-cards/",
  "/it/prodotto/car-transponder-chip": "/products/rfid-tags/",
  "/it/prodotto/carta-legale": "/",
  "/it/prodotto/hitag-2-card": "/products/rfid-tags/",
  "/it/prodotto/mifare-plus-card": "/products/rfid-cards/mifare-plus-se-card/",
  "/it/prodotto/nfc-reader-writer-with-free-sdks": "/products/rfid-readers/",
  "/it/prodotto/schede-mifare-desfire-ev2": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/ja": "/",
  "/ja/%E5%95%86%E5%93%81%E3%82%BF%E3%82%B0/rfid-key-tags": "/products/rfid-tags/",
  "/ja/%E8%A3%BD%E5%93%81/%E3%82%B8%E3%83%A3%E3%83%90%E3%82%AB%E3%83%BC%E3%83%89": "/",
  "/ja/%E8%A3%BD%E5%93%81/%E3%83%92%E3%82%BF%E3%82%B02%E3%82%AB%E3%83%BC%E3%83%89": "/",
  "/ja/%E8%A3%BD%E5%93%81/mifare-plus%E3%82%AB%E3%83%BC%E3%83%89": "/products/rfid-cards/mifare-plus-se-card/",
  "/ja/%E8%A3%BD%E5%93%81/nfc-reader-writer-with-free-sdks": "/products/rfid-readers/",
  "/ja/%E8%A3%BD%E5%93%81/nfc-ring": "/products/rfid-wristbands/",
  "/ja/about": "/about/",
  "/ja/blog": "/",
  "/product-category/products/rfid-readers": "/products/rfid-cards/",
  "/pt": "/",
  "/pt/about": "/about/",
  "/pt/etiqueta-do-produto/nfc-tap-here-sticker": "/products/rfid-labels/",
  "/pt/produto/java-card": "/products/rfid-cards/",
  "/pt/produto/mifare-desfire-ev2-cards": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/pt/produto/mifare-plus-card": "/products/rfid-cards/mifare-plus-se-card/",
  "/pt/produto/uhf-wristband": "/products/rfid-wristbands/",
  "/pt/produto/wooden-rfid-card": "/products/rfid-cards/",
  "/ru/%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B0/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D1%8B/rfid-labels": "/products/rfid-labels/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/%D1%81%D0%B8%D0%BB%D0%B8%D0%BA%D0%BE%D0%BD%D0%BE%D0%B2%D1%8B%D0%B5-%D0%B1%D1%80%D0%B0%D1%81%D0%BB%D0%B5%D1%82%D1%8B-rfid": "/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/car-transponder-chip": "/products/rfid-tags/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/felica-card": "/products/rfid-cards/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/hitag-2-card": "/products/rfid-tags/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/java-card": "/products/rfid-cards/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/mifare-desfire-cards": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/mifare-plus-card": "/products/rfid-cards/mifare-plus-se-card/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/mifare-stickers": "/products/rfid-labels/",
  "/ru/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82/nfc-%D1%80%D0%B8%D0%B4%D0%B5%D1%80-%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D0%B5%D0%BB%D1%8C-%D1%81-%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D1%8B%D0%BC%D0%B8-sdk": "/products/rfid-readers/",
  "/ru/%D1%82%D0%B5%D0%B3-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B0/%D0%B2%D0%BE%D0%B4%D0%BE%D0%BD%D0%B5%D0%BF%D1%80%D0%BE%D0%BD%D0%B8%D1%86%D0%B0%D0%B5%D0%BC%D1%8B%D0%B9-%D0%B1%D1%80%D0%B0%D1%81%D0%BB%D0%B5%D1%82-rfid": "/",
  "/ru/%D1%82%D0%B5%D0%B3-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B0/mifare-classic-1k-%D0%BD%D0%B0%D0%BA%D0%BB%D0%B5%D0%B9%D0%BA%D0%B0": "/products/rfid-cards/mifare-classic-1k-card/",
  "/ru/%D1%82%D0%B5%D0%B3-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B0/rfid-custom-wristbands": "/products/rfid-wristbands/",
  "/ru/%D1%82%D0%B5%D0%B3-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B0/rfid-silicone-wristband": "/products/rfid-wristbands/",
  "/ru/about": "/about/",
  "/shop": "/",
  "/shop/page/2": "/",
  "/tr": "/",
  "/tr/2025/11/04/mifare_plus_card": "/products/rfid-cards/",
  "/tr/blog": "/",
  "/tr/sss": "/",
  "/tr/urun/hotel-key-cards": "/products/rfid-cards/",
  "/tr/urun/mifare-desfire-ev2-cards": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/tr/urun/nfc-reader-writer-with-free-sdks": "/products/rfid-readers/",
  "/zh": "/",
  "/zh/%E4%BA%A7%E5%93%81/java-card": "/products/rfid-cards/",
  "/zh/%E4%BA%A7%E5%93%81/mifare-desfire-ev2%E5%8D%A1": "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/zh/%E6%8E%A5%E8%A7%A6": "/",
  "/zh/blog": "/",

  /* ── Compare-cluster collapses ──────────────────────────────────────── */
  "/compare/mifare-plus-vs-desfire/": "/compare/mifare-plus-ev2-vs-desfire-ev3/",
  "/compare/pps-vs-silicone-laundry-tags/": "/compare/pps-vs-silicone-vs-textile-rfid-laundry-tags/",

  /* ── Legacy /product/* WP stub → content-collection landing (W3-4d⁵) ──
   * The 51 WP-era /product/* pages duplicate newer content-collection SKUs,
   * solution landings, or compare pages. Each entry points the legacy URL
   * at its richer equivalent:
   *   - canonical <link> on the stub page points here (seo.ts)
   *   - internal <a href> rewriting redirects old links here (rewriteLegacyInternalLinks)
   *   - collectCatalogProducts() drops stubs that have a canonical override
   *     from the /products/all/ filter grid (catalog-pages.ts)
   *
   * Stubs stay buildable as soft-landing pages so existing inbound links
   * don't 404, but all first-party navigation routes users to the canonical.
   */

  /* HF + NFC cards → content-collection rfid-cards SKUs */
  "/product/nfc-sticker/":                   "/products/rfid-labels/ntag213-nfc-sticker/",
  "/product/nfc-stickers/":                  "/products/rfid-labels/ntag213-nfc-sticker/",
  "/product/mifare-stickers/":               "/products/rfid-labels/ntag213-nfc-sticker/",
  "/product/mifare-classic-card/":           "/products/rfid-cards/mifare-classic-1k-card/",
  "/product/mifare-4k-card/":                "/products/rfid-cards/mifare-classic-1k-card/",
  "/product/mifare-plus-card/":              "/products/rfid-cards/mifare-plus-se-card/",
  "/product/mifare-desfire-cards/":          "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/product/mifare-desfire-ev2-cards/":      "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/product/desfire-tag/":                   "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/product/java-card/":                     "/products/rfid-cards/",
  "/product/dual-interface-card/":           "/products/rfid-cards/dual-frequency-rfid-card/",
  "/product/combi-card/":                    "/products/rfid-cards/dual-frequency-rfid-card/",
  "/product/metal-nfc-card/":                "/products/rfid-cards/rfid-metal-business-card/",
  "/product/wooden-rfid-card/":              "/products/rfid-cards/rfid-wooden-card/",
  "/product/eco_rfid_card/":                 "/products/rfid-cards/rfid-bamboo-card/",
  "/product/rfid-paper-card/":               "/products/rfid-cards/rfid-bamboo-card/",
  "/product/inkjet-pvc-id-card/":            "/products/rfid-cards/nfc-card-custom-printing/",
  "/product/printed-rfid-cards/":            "/products/rfid-cards/nfc-card-custom-printing/",
  "/product/blank-rfid-card/":               "/products/rfid-cards/nfc-card-custom-printing/",

  /* LF cards → EM4100 rfid-card equivalent */
  "/product/125-khz-rfid-card/":             "/products/rfid-cards/em4100-rfid-card/",
  "/product/em4200-card/":                   "/products/rfid-cards/em4100-rfid-card/",
  "/product/em4305-card/":                   "/products/rfid-cards/em4100-rfid-card/",
  "/product/t5577-card/":                    "/products/rfid-cards/em4100-rfid-card/",

  /* Cards without a direct SKU equivalent → rfid-cards pillar */
  "/product/125khz-rfid-sticker/":           "/products/rfid-labels/",
  "/product/clamshell-card/":                "/products/rfid-cards/",
  "/product/felica-card/":                   "/products/rfid-cards/",
  "/product/hitag-2-card/":                  "/products/rfid-cards/",
  "/product/legic-card/":                    "/products/rfid-cards/",
  "/product/nfc-cards/":                     "/products/rfid-cards/",

  /* Solution pages for cross-category landings */
  "/product/nfc-business-card/":             "/solutions/nfc-business-card/",
  "/product/google-review-nfc-card/":        "/solutions/google-review-nfc-card/",
  "/product/hotel-key-cards/":               "/solutions/hotel-key-cards/",

  /* Wristbands */
  "/product/rfid-event-wristband/":          "/solutions/rfid-event-wristbands/",
  "/product/rfid-wristbands-for-events/":    "/solutions/rfid-event-wristbands/",
  "/product/rfid-wristbands-for-hotels/":    "/solutions/rfid-event-wristbands/",
  "/product/rfid-silicone-wristbands/":      "/products/rfid-wristbands/rfid-adjustable-silicone-wristband/",
  "/product/coconut-shell-rfid-wristband/":  "/products/rfid-wristbands/",
  "/product/uhf-wristband/":                 "/products/rfid-wristbands/uhf-rfid-wristband/",
  "/product/nfc-ring/":                      "/products/rfid-wristbands/",

  /* Keyfobs */
  "/product/rfid-key-fob/":                  "/products/rfid-keyfobs/",
  "/product/proximity-fobs/":                "/products/rfid-keyfobs/",

  /* Laundry + on-metal tags */
  "/product/rfid-laundry-tags/":             "/solutions/rfid-laundry-tags/",
  "/product/rfid-silicone-laundry-tag/":     "/products/rfid-tags/rfid-high-temp-silicone-tag/",
  "/product/pps-rfid-laundry-tag/":          "/products/rfid-tags/rfid-pps-laundry-chip/",

  /* Merged SKUs — rfid-on-metal-uhf-tag absorbed into rfid-anti-metal-tag (2026-04-23) */
  "/products/rfid-tags/rfid-on-metal-uhf-tag/": "/products/rfid-tags/rfid-anti-metal-tag/",

  /* Vehicle / windshield */
  "/product/car-transponder-chip/":          "/solutions/vehicle-rfid-identification/",
  "/product/rfid-sticker-on-headlight/":     "/products/rfid-labels/long-range-uhf-windshield-sticker/",
  "/product/rfid-windshield-tag/":           "/products/rfid-labels/long-range-uhf-windshield-sticker/",
  "/product/rfid-tag-with-led-light/":       "/products/rfid-tags/",

  /* Hardware (readers / scanners) → rfid-readers cluster SKUs */
  "/product/acr122u/":                       "/products/rfid-readers/desktop-nfc-reader-encoder/",
  "/product/bluetooth-rfid-scanner/":        "/products/rfid-readers/handheld-uhf-rfid-reader/",
  "/product/nfc-reader-writer-with-free-sdks/": "/products/rfid-readers/desktop-nfc-reader-encoder/",

  /* Batch 40 / wristband-card dedup collapses — mirror vercel.json + _redirects
     so rewriteLegacyInternalLinks fixes in-content links too. */
  "/products/rfid-wristbands/nfc-payment-wristband/":  "/products/rfid-wristbands/cashless-payment-rfid-wristband/",
  "/products/rfid-wristbands/tyvek-rfid-wristband/":   "/products/rfid-wristbands/rfid-tyvek-wristband/",
  "/products/rfid-cards/mifare-ultralight-c-cards/":   "/products/rfid-cards/mifare-ultralight-c-card/",
  "/products/rfid-cards/mifare-desfire-ev3-cards/":    "/products/rfid-cards/mifare-desfire-ev3-card/",
  "/products/rfid-cards/rfid-dual-frequency-card/":    "/products/rfid-cards/dual-frequency-rfid-card/",
  "/products/rfid-cards/transparent-clear-nfc-card/":  "/products/rfid-cards/transparent-nfc-card/",

  /* Cannibalization collapses — same-intent twins → strongest page
     (2026-06-10, user-approved; unique loser content folded into survivors).
     Mirrored in vercel.json + public/_redirects. */
  "/blog/ntag213-vs-ntag215-vs-ntag216/":              "/compare/ntag213-vs-ntag215-vs-ntag216/",
  "/blog/em4100-vs-t5577-125khz-comparison/":          "/compare/em4100-vs-t5577/",
  "/blog/magnetic-stripe-vs-rfid-hotel-cards/":        "/compare/rfid-vs-magnetic-hotel-key-cards/",
  "/compare/rfid-hotel-card-vs-magnetic-stripe/":      "/compare/rfid-vs-magnetic-hotel-key-cards/",
  "/blog/pps-vs-silicone-vs-textile-laundry-tags/":    "/compare/pps-vs-silicone-vs-textile-rfid-laundry-tags/",
  "/blog/silicone-vs-fabric-vs-tyvek-wristbands/":     "/compare/silicone-vs-fabric-vs-woven-rfid-wristbands/",
  "/blog/how-to-choose-rfid-wristband-material/":      "/compare/silicone-vs-fabric-vs-woven-rfid-wristbands/",
  "/blog/hotel-key-card-encoding-explained/":          "/guides/hotel-key-card-encoding/",
  "/blog/hotel-key-card-design-printing/":             "/guides/hotel-key-card-artwork-and-printing-checklist/",
  "/blog/walmart-rfid-mandate-2026-supplier-compliance/": "/guides/walmart-rfid-tagging-mandate/",
  "/blog/rfid-laundry-system-payback-period/":         "/blog/rfid-laundry-system-roi/",
  "/blog/rfid-wristbands-music-festival-2026/":        "/blog/rfid-wristbands-festivals-events/",
  "/about/case-studies/":                              "/case-studies/",

  /* lp doorway-cluster consolidation — 16 → 12 pages (2026-06-10,
     user-approved option (a): merge near-duplicates, expand survivors). */
  "/lp/rfid-factory-direct-china/":                    "/lp/rfid-manufacturer-shenzhen/",
  "/lp/rfid-solution-provider/":                       "/lp/rfid-manufacturer-shenzhen/",
  "/lp/nfc-tag-supplier/":                             "/lp/nfc-tag-manufacturer-china/",
  "/lp/uhf-rfid-tag-manufacturer/":                    "/lp/rfid-tag-factory/",
};
