/**
 * Raster twins for SVG hero diagrams — audit 2026-09-01, Phase 2 T6 / Phase 14 B6.
 *
 * 125 editorial pages use an SVG diagram as `heroImage`, and that URL used to
 * flow straight into `og:image`, `twitter:image` and the JSON-LD `image`
 * property. Facebook, LinkedIn, X and Google Discover do not render SVG
 * previews, so shared links showed no image at all. Every SVG hero now has a
 * pre-rendered 1200×630 JPEG twin committed under `public/og/<same path>.jpg`
 * (generated by `scripts/build-og-rasters.mjs`; the vitest in
 * `src/lib/__tests__/og-rasters.test.ts` fails when a twin is missing).
 *
 * The on-page hero keeps the crisp inline SVG; only the machine-facing image
 * references switch to the raster. An SVG without a twin falls through
 * unchanged, so a missing file can never break the build.
 */
import { existsSync, readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

export const OG_RASTER_PREFIX = "/og";
const OG_DIR = join(process.cwd(), "public", "og");

let rasterPaths: Set<string> | null = null;

function walk(dir: string, out: Set<string>): void {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, out);
    } else if (/\.jpe?g$/i.test(entry)) {
      out.add(`${OG_RASTER_PREFIX}/${relative(OG_DIR, full).split(sep).join("/")}`);
    }
  }
}

/** All committed raster paths as root-relative URLs, e.g. `/og/diagrams/blog/x.jpg`. */
export function listOgRasterPaths(): ReadonlySet<string> {
  if (!rasterPaths) {
    rasterPaths = new Set<string>();
    if (existsSync(OG_DIR)) walk(OG_DIR, rasterPaths);
  }
  return rasterPaths;
}

/** The raster path an SVG url WOULD have (whether or not the file exists). */
export function expectedOgRasterPath(svgUrl: string): string | null {
  let pathname = svgUrl;
  try {
    if (/^https?:\/\//i.test(svgUrl)) pathname = new URL(svgUrl).pathname;
  } catch {
    return null;
  }
  if (!/\.svg$/i.test(pathname)) return null;
  return `${OG_RASTER_PREFIX}${pathname.replace(/\.svg$/i, ".jpg")}`;
}

/**
 * Root-relative raster path for an SVG url when its twin exists, else null.
 * Non-SVG urls always return null (callers keep the original).
 */
export function toOgRasterPath(url: string): string | null {
  const expected = expectedOgRasterPath(url);
  if (!expected) return null;
  return listOgRasterPaths().has(expected) ? expected : null;
}

/** Test seam — forget the cached directory listing. */
export function resetOgRasterCache(): void {
  rasterPaths = null;
}
