/**
 * Cheerio sanitizers for the WordPress-imported page <head> and <body>.
 *
 * sanitizeHead strips `<title>`, `<meta>`, `<link rel=…>` etc. that are
 * regenerated by buildPageSeo to avoid duplicates after our overrides
 * are emitted.
 *
 * sanitizeBody strips inline scripts, WP / WooCommerce admin remnants,
 * tracking pixels and other DOM artifacts that don't belong on a static
 * marketing page.
 *
 * Extracted from seo.ts during the P4d-1 split (2026-05-08).
 */
import type { CheerioAPI } from "cheerio";

import { cleanText } from "./utils";

export function sanitizeHead($head: CheerioAPI): void {
  [
    "title",
    'meta[name="description"]',
    'meta[name="robots"]',
    'meta[name="msapplication-TileImage"]',
    'link[rel="canonical"]',
    'meta[property^="og:"]',
    'meta[name^="twitter:"]',
    'meta[property^="article:"]',
    'script[type="application/ld+json"]',
    'link[rel="alternate"][type="application/json"]',
    'link[rel="alternate"][type*="oembed"]',
    'link[rel="https://api.w.org/"]',
    'link[rel="EditURI"]',
    'link[rel="shortlink"]',
    'script[src*="accounts.google.com/gsi/client"]',
    'script[src*="google-site-kit"]',
    'script[id*="googlesitekit"]',
    'script[src*="wp-statistics"]',
    'script[id*="wp-statistics"]',
    'style[id="wp-emoji-styles-inline-css"]',
    'meta[name="generator"]',
    'meta[name^="google-adsense-platform"]',
    // P0-HEAD-BLOAT-SAFE (PR audit/p0-seo-indexability): drop pure duplicates
    // emitted by both Astro <SeoHead> AND the WP chrome snapshot. Astro
    // already emits these via partials/SeoHead.astro, so the second copy
    // is dead bytes (~150-300 B per page across 605 pages = ~100 KB total).
    "meta[charset]",
    'meta[name="viewport"]',
    'meta[http-equiv="X-UA-Compatible"]',
    // WP injects `<link rel="dns-prefetch" href="https://www.googletagmanager.com/">`
    // duplicating the `<link rel="preconnect">` we declare in SeoHead. preconnect
    // already includes DNS resolution so the prefetch is strictly redundant.
    'link[rel="dns-prefetch"]',
    // PR-3 P0-HEAD-BLOAT (conservative tier): strip WP/WooCommerce style blocks
    // that the Astro editorial tree never uses. KEEP every Kadence stylesheet
    // and `kadence-*-inline-css` block — `codex-tokens.css` references the
    // Kadence palette vars (`--global-palette1..9`, `--global-content-width`
    // etc.) and visual regressions would surface site-wide. Aggressive Kadence
    // theme stripping (with a brand-palette critical-CSS stub) is deferred to
    // a follow-up PR pending visual diffing.
    //
    //   - wp-block-library-css → Gutenberg block editor base CSS; Astro
    //     editorial components emit `codex-*` classes, not `wp-block-*`.
    //   - classic-theme-styles-inline-css → block editor classic-theme
    //     shims; never matched by Astro-rendered DOM.
    //   - woocommerce-inline-inline-css → e-commerce UI (no shop here).
    //   - wc-blocks-style → WooCommerce blocks (no shop here).
    //   - wp-block-* → all remaining individual WP block CSS bundles.
    //
    // Each WP page typically ships 5–15 KB of these blocks; with 605 pages
    // that's 3–10 MB of dead transfer per crawl. Lighthouse "Unused CSS"
    // also flags these in the Performance score breakdown.
    'link[id="wp-block-library-css"]',
    'link[id="wp-block-library-theme-css"]',
    'link[id^="wp-block-"]',
    'link[id="wc-blocks-style-css"]',
    'link[id="classic-theme-styles-css"]',
    'style[id="classic-theme-styles-inline-css"]',
    'style[id="woocommerce-inline-inline-css"]',
    'style[id="wc-blocks-style-inline-css"]',
  ].forEach((selector) => {
    $head(selector).remove();
  });

  $head("script").each((_, element) => {
    const content = cleanText($head(element).html() ?? "");

    if (
      content.includes("WP_Statistics_Tracker_Object") ||
      content.includes("_googlesitekit") ||
      content.includes("googletagmanager") ||
      content.includes("_wpemojiSettings") ||
      content.includes("wpEmojiSettingsSupports")
    ) {
      $head(element).remove();
    }
  });
}

export function sanitizeBody($body: CheerioAPI): void {
  [
    "meta",
    "title",
    "base",
    'link[rel="canonical"]',
    'link[rel="alternate"]',
    'link[rel="shortlink"]',
    'link[rel="EditURI"]',
    'link[rel="https://api.w.org/"]',
    'script[type="application/ld+json"]',
    'script[src*="accounts.google.com/gsi/client"]',
    'script[src*="google-site-kit"]',
    'script[src*="wp-statistics"]',
    'script[id*="googlesitekit"]',
    'script[id*="wp-statistics"]',
    ".googlesitekit-sign-in-with-google__frontend-output-button",
  ].forEach((selector) => {
    $body(selector).remove();
  });

  $body("script").each((_, element) => {
    const content = cleanText($body(element).html() ?? "");

    if (content.includes("WP_Statistics_Tracker_Object") || content.includes("_googlesitekit")) {
      $body(element).remove();
      return;
    }

    // Defer remaining non-critical render-blocking scripts for better LCP
    // (jQuery/WooCommerce/cookie scripts are already fully stripped in render-snapshot.ts)
    const src = ($body(element).attr("src") ?? "").toLowerCase();
    if (
      src &&
      !$body(element).attr("async") &&
      !$body(element).attr("defer") &&
      (src.includes("jarallax") ||
        src.includes("parallax") ||
        src.includes("kb-advanced"))
    ) {
      $body(element).attr("defer", "");
    }
  });

  $body('footer a[href=""], footer a[href="#"], footer a[href="tel:"], footer a[href="mailto:"]').remove();
  $body("footer .footer-social-wrap, footer .header-social-wrap").each((_, element) => {
    if ($body(element).find("a[href]").length === 0) {
      $body(element).remove();
    }
  });

  // Remove empty breadcrumb entries (ghost links with no text that cause double slashes)
  $body(".kadence-breadcrumb-container span").each((_, element) => {
    const $span = $body(element);
    const link = $span.find("a");
    if (link.length > 0 && !cleanText(link.text())) {
      // Remove the empty breadcrumb span and the following delimiter
      const next = $span.next(".bc-delimiter");
      if (next.length) next.remove();
      $span.remove();
    }
  });
}

