/**
 * Cheerio sanitizers for the WordPress-imported page <head> and <body>.
 *
 * sanitizeHead strips `<title>`, `<meta>`, `<link rel=…>` etc. that are
 * regenerated by buildPageSeo to avoid duplicates after our overrides
 * are emitted.
 *
 * sanitizeBody strips inline scripts, WP / WooCommerce admin remnants,
 * tracking pixels and other DOM artifacts that don't belong on a static
 * marketing page.
 *
 * Extracted from seo.ts during the P4d-1 split (2026-05-08).
 */
import type { CheerioAPI } from "cheerio";

import { cleanText } from "./utils";

export function sanitizeHead($head: CheerioAPI): void {
  [
    "title",
    'meta[name="description"]',
    'meta[name="robots"]',
    'meta[name="msapplication-TileImage"]',
    'link[rel="canonical"]',
    'meta[property^="og:"]',
    'meta[name^="twitter:"]',
    'meta[property^="article:"]',
    'script[type="application/ld+json"]',
    'link[rel="alternate"][type="application/json"]',
    'link[rel="alternate"][type*="oembed"]',
    'link[rel="https://api.w.org/"]',
    'link[rel="EditURI"]',
    'link[rel="shortlink"]',
    'script[src*="accounts.google.com/gsi/client"]',
    'script[src*="google-site-kit"]',
    'script[id*="googlesitekit"]',
    'script[src*="wp-statistics"]',
    'script[id*="wp-statistics"]',
    'style[id="wp-emoji-styles-inline-css"]',
    'meta[name="generator"]',
    'meta[name^="google-adsense-platform"]',
  ].forEach((selector) => {
    $head(selector).remove();
  });

  $head("script").each((_, element) => {
    const content = cleanText($head(element).html() ?? "");

    if (
      content.includes("WP_Statistics_Tracker_Object") ||
      content.includes("_googlesitekit") ||
      content.includes("googletagmanager") ||
      content.includes("_wpemojiSettings") ||
      content.includes("wpEmojiSettingsSupports")
    ) {
      $head(element).remove();
    }
  });
}

export function sanitizeBody($body: CheerioAPI): void {
  [
    "meta",
    "title",
    "base",
    'link[rel="canonical"]',
    'link[rel="alternate"]',
    'link[rel="shortlink"]',
    'link[rel="EditURI"]',
    'link[rel="https://api.w.org/"]',
    'script[type="application/ld+json"]',
    'script[src*="accounts.google.com/gsi/client"]',
    'script[src*="google-site-kit"]',
    'script[src*="wp-statistics"]',
    'script[id*="googlesitekit"]',
    'script[id*="wp-statistics"]',
    ".googlesitekit-sign-in-with-google__frontend-output-button",
  ].forEach((selector) => {
    $body(selector).remove();
  });

  $body("script").each((_, element) => {
    const content = cleanText($body(element).html() ?? "");

    if (content.includes("WP_Statistics_Tracker_Object") || content.includes("_googlesitekit")) {
      $body(element).remove();
      return;
    }

    // Defer remaining non-critical render-blocking scripts for better LCP
    // (jQuery/WooCommerce/cookie scripts are already fully stripped in render-snapshot.ts)
    const src = ($body(element).attr("src") ?? "").toLowerCase();
    if (
      src &&
      !$body(element).attr("async") &&
      !$body(element).attr("defer") &&
      (src.includes("jarallax") ||
        src.includes("parallax") ||
        src.includes("kb-advanced"))
    ) {
      $body(element).attr("defer", "");
    }
  });

  $body('footer a[href=""], footer a[href="#"], footer a[href="tel:"], footer a[href="mailto:"]').remove();
  $body("footer .footer-social-wrap, footer .header-social-wrap").each((_, element) => {
    if ($body(element).find("a[href]").length === 0) {
      $body(element).remove();
    }
  });

  // Remove empty breadcrumb entries (ghost links with no text that cause double slashes)
  $body(".kadence-breadcrumb-container span").each((_, element) => {
    const $span = $body(element);
    const link = $span.find("a");
    if (link.length > 0 && !cleanText(link.text())) {
      // Remove the empty breadcrumb span and the following delimiter
      const next = $span.next(".bc-delimiter");
      if (next.length) next.remove();
      $span.remove();
    }
  });
}

